# Generated by Django 4.1.7 on 2023-03-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='Adress',
            new_name='Address',
        ),
    ]
