# Generated by Django 4.1.7 on 2023-03-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_adress_customers_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Phone',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
