# Generated by Django 4.1.7 on 2023-03-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_customers_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
